### ISSUE TITLE
This package depends on nvidia-ml-py3 which is quite old, could it use nvidia-ml-py instead?

### ISSUE THREAD

**Issue by mattip** [slothfulxtx/TransLoc3D#4]
As the title states, there is a dependency on the obsolete nvidia-ml-py3 in the [requirements.txt](https://github.com/slothfulxtx/TransLoc3D/blob/1ccf1b9f0e283fcbc6e042a8504cd1d319eaa8d8/requirements.txt#L71). But this makes the package incompatible with gpustat, since it requires nvidia-ml-py (without the 3) instead. This trips up ray, here is the relevant discussion https://github.com/wookayin/gpustat/pull/107#issuecomment-1189837063

**Comment by slothfulxtx** [comment]
I suppose it could work, because no packages except for gpustat require nvidia-ml-py3.

Reguards,
Tian-Xing Xu
